In [13]:
import numpy as np
d=np.array([1])
a=np.array([1,2])
b=np.array([[1,2],[3,4]])
c=np.array([[[1,2],[3,4]],[[6,6],[1,2]]])




In [16]:
a


array([1, 2])

In [18]:
d

array([1])

In [20]:
c


array([[[1, 2],
        [3, 4]],

       [[6, 6],
        [1, 2]]])

In [22]:
b

array([[1, 2],
       [3, 4]])